Fix the "all tasks" option
kraken-build/kraken-core pull request #37
Opened 2023-04-11 16:14 UTC by daladim

Before this PR, `kraken` considered `--all`as a distinct argument from a task list.
However, this would make more sense for this option to be mutually exclusive from a task list, and (since I did not think of a more sensible default value), this should be the default value when no task list is given.
This is what this PR is doing.

It is also fixing a bug, where kraken was not able to find the tasks when `--all` was used

2023-04-12 09:54 UTC, NiklasRosenstein commented on src/kraken/core/cli/option_sets.py
> +            "tasks", metavar="task", nargs="*", help="one or more tasks to execute. If not set, consider all tasks"
There's a difference between `--all` and "not specifying any tasks". If you don't specify any tasks, all tasks that have the `Task.default` flag set to `True` are supposed to be selected, which is quite different from selecting every single task.

2023-04-17 16:33 UTC, daladim commented
OK, so I think I have now fixed the exisitng bugs. To sum up:
* the CLI syntax makes it clear that we can either call `kraken <action>`, or `kraken <action> specified-tasks ...`, or `kraken <action> --all`, but not `kraken <action> --all specified-tasks`
* this fixes `kraken <action>`, that, since #23 or #30 (not sure), raised an exception that reads `ValueError: ':' refers to no tasks.`


Still left TODO: It now selects all default tasks from the current project (but should include sub projects). Use `kraken <action> :` to restrict to the default tasks of the current project only.

2023-04-18 08:23 UTC, daladim commented
This MR now correctly supports sub-projects.
* `kraken q ls` selects default tasks from the current project and its children (recursively)
* `kraken q ls :` restricts to the current project

2023-04-19 09:20 UTC, ntrinquier requested changes

2023-04-19 09:20 UTC, ntrinquier commented on src/kraken/core/address/_address.py
>          """Parses a list or strings or lists into (is_absolute, elements)."""
need to update the docs string too

2023-04-19 09:20 UTC, ntrinquier commented on src/kraken/core/address/_address.py
> +            element_strings.pop(-1)
nit

```suggestion
        is_container = element_strings and not element_strings[-1]
        if is_container:
            element_strings.pop(-1)
```

2023-04-19 09:20 UTC, ntrinquier commented on src/kraken/core/address/_address.py
> +        value = Address.SEPARATOR.join(str(x) for x in self._elements)
👍🏼

2023-04-19 09:20 UTC, ntrinquier commented on src/kraken/core/address/_address_resolver.py
> +        return len(list(space.get_children(addr))) > 0
nit (it avoids casting to a list, even if the impact is not huge)
```suggestion
        return any(True for _ in iterator)
```

2023-04-19 13:03 UTC, NiklasRosenstein reviewed
Thanks @daladim, I'm in favor of these changes. Left a few comments!

2023-04-19 13:03 UTC, NiklasRosenstein commented on src/kraken/core/system/context.py
> +            tasks = self.resolve_tasks([])
This is inconsistent with the semantic changes of `resolve_tasks()` above.

2023-04-19 13:03 UTC, NiklasRosenstein commented on tests/test_task_addresses.py
> +        tasks = context.resolve_tasks([":subproject_task"])
```suggestion
       context.resolve_tasks([":subproject_task"])
```

nit

2023-04-19 13:03 UTC, NiklasRosenstein commented on tests/test_task_addresses.py
> +    kraken_project.do("task", VoidTask, default=True)
Any reason to use a `default` and a `task` task which both have the same configuration? Seems like it doesn't add value to the test and is confusing the the test reader.

2023-04-19 16:12 UTC, daladim commented on src/kraken/core/cli/option_sets.py
> +        selection = group.add_mutually_exclusive_group()
I'm not sure what you mean here.
Do you want me to remove the ability to invoke `kraken run --all`? (this invocation does indeed not sound very useulf, but, well, why not keep it).
Or do you want me to support `kraken run --all python.install`? (But what would the expected result be? Is it really used anywhere? Or would a `kraken run python.install ; kraken run --all` be a good enough solution?)
Thanks

2023-04-19 16:14 UTC, daladim commented on src/kraken/core/address/_address.py
> +            element_strings.pop(-1)
Indeed. Thanks

2023-04-19 16:20 UTC, daladim commented on tests/test_task_addresses.py
> +    kraken_project.do("task", VoidTask, default=True)
The main reason is to test that `:` indeed resolves to multiple tasks and not just one.
But you're right that it can be confusing. I've renamed them to `default1` and `default2`

2023-04-19 16:46 UTC, daladim commented on src/kraken/core/address/_address.py
> +            element_strings.pop(-1)
Actually, `mypy` does not like it, unless we add a `is not None and element_strings != []`, so that's finally not as concise as we would like.

I think I'll stick to the previous version

2023-04-20 09:16 UTC, daladim commented on src/kraken/core/address/_address.py
> +            value = f"{value}{Address.SEPARATOR}"
Nice catch. Also, `:` is both absolute _and_ a container. I'll add tests (and will fix this)

2023-04-21 08:12 UTC, NiklasRosenstein commented on src/kraken/core/cli/option_sets.py
> +        selection = group.add_mutually_exclusive_group()
`krakenw run --all python.install` would run all tasks (by not trimming the graph), and set the `Task.selected` attribute of the `python.install` task to `True` (which alters the behavior of the task).

Sorry for the mixed messaging; first I wanted to point out that there is a semantic difference to `--all` vs. `--all python.install`, and then I conjectured that `--all` might not be very useful in `kraken run` at all.

I think we might just want to consider to remove the `--all` flag from run 🙃

2023-04-21 08:15 UTC, NiklasRosenstein commented on src/kraken/core/address/_address.py
> +            if value and value[-1] != Address.SEPARATOR:
```suggestion
        if self._is_container and not self._is_absolute:
```

2023-04-21 08:18 UTC, NiklasRosenstein commented on src/kraken/core/address/_address.py
> +        obj._is_container = is_container
I wonder if we should add an assertion here or some logic to normalize the state for the semantic overlap.

* If there are no elements, and `is_absolute` is Tre, then `is_container` must be `True`.
* If there are no elements, and `is_container` is True, `is_absolute` must be True.

2023-04-21 08:21 UTC, NiklasRosenstein commented on src/kraken/core/system/context.py
> +            tasks = self.resolve_tasks([":"])
> either all default tasks

I think that means we must default to `[":", ":**:"]` as you are using it in `_load_build_state()`.

Basically it boils down to making `resolve_tasks()` accept `None` again and making it behave like `[":", ":**:"]` :)

2023-04-21 09:01 UTC, daladim commented on src/kraken/core/system/context.py
> +            tasks = self.resolve_tasks([":"])
Well, I'm hiding dust under the carpet here.
`:**:` raises an exception in case there is no sub-project. That's why I removed the "None becomes `[":", ":**:"]`" conversion from `resolve_tasks()`, and moved it into `main.py`, which is able to ignore the exception when `:**:` is requested (but not in case a different address is requested).

But I think you are right, this logic should be taken into account here as well.
I'll see what sensible solution I can do

2023-04-21 09:12 UTC, daladim commented on src/kraken/core/address/_address.py
> +            if value and value[-1] != Address.SEPARATOR:
Hmmm, I don't think this is what we want.
`:a:b:c:` is both a container and absolute, and we still want the heading and trailing colon.

So I could have something like `if self._is_container and len(self._elements) > 0` instead, but, meh, is that more explicit/easier to read than the original version?

2023-04-21 09:17 UTC, daladim commented on src/kraken/core/address/_address.py
> +        obj._is_container = is_container
Good idea.

2023-04-21 12:40 UTC, daladim commented on src/kraken/core/cli/option_sets.py
> +        selection = group.add_mutually_exclusive_group()
All right. I've removed the `--all` option from `kraken run`.

2023-04-22 09:52 UTC, NiklasRosenstein commented on src/kraken/core/address/_address.py
> +            if value and value[-1] != Address.SEPARATOR:
Ah yes, you are correct. I do find what you suggest in your last comment easier as it expresses the logic in the language of what constitutes an Address, rather than in the context that is built up incrementally.

2023-04-22 10:10 UTC, NiklasRosenstein requested changes

2023-04-22 10:10 UTC, NiklasRosenstein commented on src/kraken/core/cli/option_sets.py
> +                help="one or more tasks to select. If not set, default tasks are selected",
Same as below; "selection" happens by way of explicitly mentioning a task with this argument.

This is probably something we should document somewhere:

* You start with all tasks in the graph
* Unless `--all` is specified, you trim the graph to contain only the "targeted" tasks
  * The set of "target tasks" is either all that have been selected explicitly via the CLI; or all default tasks
* All "selected" tasks get their `Task.selected` flag enabled (this is zero tasks if no tasks are mentioned on the CLI and we fall back to the "default" tasks as the targets)

2023-04-22 10:10 UTC, NiklasRosenstein commented on src/kraken/core/cli/option_sets.py
> +            all = args.all
```suggestion
            all_ = getattr(args, "all", False)
```

nit: slimmer this way, and avoid overriding built ins (can pass this one liner as an argument again)

2023-04-22 10:10 UTC, NiklasRosenstein commented on src/kraken/core/system/context.py
> +            raise TaskResolutionException(f"'relative_to' must be an absolute address (got {relative_to!r})")
I would consider this a contract in the API, thus a non absolute Address is an invalid value to pass into the function.

It is something the caller can foresee; whereas they cannot foresee whether a valid address will resolve successfully or not.

```suggestion
            raise ValueError(f"'relative_to' must be an absolute address (got {relative_to!r})")
```

2023-05-11 17:23 UTC, NiklasRosenstein approved these changes

2023-05-11 17:23 UTC, merged